version: "2.4"
services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - /mnt/c/source/Sourcify/redis_data:/data
    environment:
      - TZ=UTC
    command: "--save 60 1 --loglevel warning"
    ports:
      - "6379:6379"
