version: "2.4"
services:
  abi_parser:
    image: abi_parser:1
    build: AbiParser
    container_name: abi_parser
    volumes:
      - /media/md/bb53783f-9c30-4067-8105-3337e14ac816/sourcify:/data
    depends_on:
      - redis
    networks:
      - sourcify
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - data_redis:/data
    environment:
      - TZ=UTC
    command: "--save 60 1 --loglevel warning"
    ports:
      - "6379:6379"
    networks:
      - sourcify
networks:
  sourcify:
    driver: bridge

volumes:
  data_redis:
    driver: local
