version: "2.4"
services:
  abi_parser:
    image: abi_parser:1
    build: AbiParser
    container_name: abi_parser
    volumes:
      - ./sourcify_data:/data
    depends_on:
      - redis
    networks:
      - sourcify
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - data_redis:/data
    environment:
      - TZ=Europe/Brussels
    command: "--save 60 1 --loglevel warning"
    ports:
      - "6379:6379"
    networks:
      - sourcify
  webapp:
    image: ultimate4bytedb:1
    build: Ultimate4ByteDb
    environment:
      - TZ=Europe/Brussels
    ports:
      - "8080:80"
    networks:
      - sourcify

networks:
  sourcify:
    driver: bridge

volumes:
  data_redis:
    driver: local
