version: "2.4"
services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./redis_data:/data
    environment:
      - TZ=Europe/Brussels
    command: "--save 60 1 --loglevel warning"
    ports:
      - "6379:6379"
    networks:
      - sourcify
  webapp:
    image: ultimate4bytedb:1
    build: Ultimate4ByteDb
    environment:
      - TZ=Europe/Brussels
    ports:
      - "8080:80"
    networks:
      - sourcify

networks:
  sourcify:
    driver: bridge
